//! gRPC protocol definitions for replication.
//!
//! Defines replication service proto (will be generated by tonic-build).

// TODO: Create proto file in proto/replication.proto
// This module will contain tonic-generated code

pub mod replication {
    // Generated code will go here
}
