apiVersion: v1
kind: Service
metadata:
  name: percolate-reading
  namespace: percolate-test
spec:
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: percolate-reading
    mode: gateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: percolate-reading-gateway
  namespace: percolate-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: percolate-reading
      mode: gateway
  template:
    metadata:
      labels:
        app: percolate-reading
        mode: gateway
    spec:
      containers:
      - name: gateway
        image: percolate-reading:v3
        imagePullPolicy: Never
        env:
        - name: MODE
          value: "gateway"
        - name: TIER
          value: "small"
        - name: S3_ENDPOINT
          value: "http://minio:9000"
        - name: S3_ACCESS_KEY
          value: "percolate"
        - name: S3_SECRET_KEY
          value: "percolate-secret"
        - name: NATS_URL
          value: "nats://nats:4222"
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
