apiVersion: keda.sh/v1alpha1
kind:ScaledJob
metadata:
  name: percolate-worker-small
  namespace: percolate-test
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: percolate-worker
          tier: small
      spec:
        restartPolicy: Never
        containers:
        - name: worker
          image: percolate-reading:v2
          imagePullPolicy: Never
          env:
          - name: MODE
            value: "worker"
          - name: TIER
            value: "small"
          - name: S3_ENDPOINT
            value: "http://minio:9000"
          - name: S3_ACCESS_KEY
            value: "percolate"
          - name: S3_SECRET_KEY
            value: "percolate-secret"
          - name: NATS_URL
            value: "nats://nats:4222"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
  pollingInterval: 10
  minReplicaCount: 0
  maxReplicaCount: 10
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  triggers:
  - type: nats-jetstream
    metadata:
      natsServerMonitoringEndpoint: "nats://nats:8222"
      account: "$G"
      stream: "jobs-small"
      consumer: "worker-small"
      lagThreshold: "5"
