apiVersion: batch/v1
kind: Job
metadata:
  name: percolate-worker-test
  namespace: percolate-test
spec:
  template:
    metadata:
      labels:
        app: percolate-worker
        tier: small
    spec:
      restartPolicy: Never
      containers:
      - name: worker
        image: percolate-reading:v3
        imagePullPolicy: Never
        env:
        - name: MODE
          value: "worker"
        - name: TIER
          value: "small"
        - name: S3_ENDPOINT
          value: "http://minio:9000"
        - name: S3_ACCESS_KEY
          value: "percolate"
        - name: S3_SECRET_KEY
          value: "percolate-secret"
        - name: NATS_URL
          value: "nats://nats:4222"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
  backoffLimit: 2
