kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-topology
nodes:
- role: control-plane
  extraPortMappings:
  # Forward port 8080 to access services
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  # Forward port 9090 for Prometheus
  - containerPort: 30090
    hostPort: 9090
    protocol: TCP
- role: worker
- role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://kind-registry:5000"]
