apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: percolate

nameSuffix: -medium

commonLabels:
  tier: medium

resources:
- ../../../components/api
- ../../../components/worker

patches:
- target:
    kind: StatefulSet
    name: api
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "2000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "2Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "2000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "2Gi"
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
      value: "100Gi"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: PERCOLATE_TIER
        value: "medium"

- target:
    kind: StatefulSet
    name: worker
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "8000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "16Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "8000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "16Gi"
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
      value: "100Gi"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: PERCOLATE_TIER
        value: "medium"
